-- 诊断员工编号 3552 的数据
-- 在 SQL Server Management Studio 中执行此脚本

USE [03546618]
GO

PRINT '=== 1. 检查员工基本信息 ==='
SELECT TOP 10
    EMPLOYEE_NO,
    EMPLOYEE_CNAME,
    EMPLOYEE_HIRE_DATE,
    LEN(EMPLOYEE_NO) as NO_LENGTH
FROM [03546618].[dbo].[vwZZ_EMPLOYEE]
WHERE EMPLOYEE_NO = '3552'

PRINT '=== 2. 使用 LIKE 搜索可能的员工编号 ==='
SELECT TOP 10
    EMPLOYEE_NO,
    EMPLOYEE_CNAME,
    EMPLOYEE_HIRE_DATE
FROM [03546618].[dbo].[vwZZ_EMPLOYEE]
WHERE EMPLOYEE_NO LIKE '%3552%'
   OR EMPLOYEE_NO = '3552'

PRINT '=== 3. 显示前20个员工记录 ==='
SELECT TOP 20
    EMPLOYEE_NO,
    EMPLOYEE_CNAME,
    EMPLOYEE_HIRE_DATE
FROM [03546618].[dbo].[vwZZ_EMPLOYEE]

PRINT '=== 4. 检查特休数据 (vwZZ_EMPLOYEE_SPECIAL) ==='
SELECT TOP 10
    EMPLOYEE_NO,
    EMPLOYEE_SPECIAL_YEAR,
    EMPLOYEE_SPECIAL_VALUE,
    SPECIAL_REMAIN_HOURS,
    IS_CLEAR
FROM [03546618].[dbo].[vwZZ_EMPLOYEE_SPECIAL]
WHERE EMPLOYEE_NO = '3552'

PRINT '=== 5. 检查补休数据 (vwZZ_EMPLOYEE_CHANGE_HOUR) ==='
SELECT TOP 10
    EMPLOYEE_NO,
    YEAR,
    CHANGE_HOURS,
    CHANGE_REMAIN_HOURS
FROM [03546618].[dbo].[vwZZ_EMPLOYEE_CHANGE_HOUR]
WHERE EMPLOYEE_NO = '3552'

PRINT '=== 6. 检查请假数据 (vwZZ_ASK_LEAVE) ==='
SELECT TOP 10
    EMPLOYEE_NO,
    LEAVE_REFERENCE_CLASS,
    ASK_LEAVE_START,
    ASK_LEAVE_HOUR
FROM [03546618].[dbo].[vwZZ_ASK_LEAVE]
WHERE EMPLOYEE_NO = '3552'

PRINT '=== 7. 检查视图列信息 ==='
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'dbo' 
  AND TABLE_NAME = 'vwZZ_EMPLOYEE'
  AND COLUMN_NAME IN ('EMPLOYEE_NO', 'EMPLOYEE_CNAME', 'EMPLOYEE_HIRE_DATE')

PRINT '=== 8. 查询所有唯一员工编号以找到相似的 ==='
SELECT DISTINCT TOP 30
    EMPLOYEE_NO,
    EMPLOYEE_CNAME
FROM [03546618].[dbo].[vwZZ_EMPLOYEE]
ORDER BY EMPLOYEE_NO
